# Generated by Django 4.2.1 on 2023-09-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('administrator', 'Admin'), ('student', 'Student'), ('profesor', 'Profesor'), ('none', 'Nema')], default='none', max_length=64),
        ),
    ]
